language: cpp
sudo: required

services:
  - docker

matrix:
  include:
    # Debian 9 (stretch).
    - env:
      - NAME=debian
      - IMAGE=debian:stretch
      - UPDATE_CMD="apt-get update"
      - UPGRADE_CMD="apt-get -y full-upgrade"
      - INSTALL_CMD="apt-get -y install autoconf automake libtool autopoint
          gettext pkg-config cmake make g++ libglib2.0-dev libpurple-dev
          libsigc++-2.0-dev libncursesw5-dev python3 doxygen graphviz"
    # Fedora 27.
    - env:
      - NAME=fedora
      - IMAGE=fedora:27
      - UPDATE_CMD="dnf makecache"
      - UPGRADE_CMD="dnf -y upgrade"
      - INSTALL_CMD="dnf -y install autoconf automake libtool gettext-devel
          pkgconfig cmake make gcc-c++ glib2-devel libpurple-devel
          libsigc++20-devel ncurses-devel doxygen graphviz"

before_install:
  - echo "Starting run ${IMAGE}"
  - docker run -d --name ${NAME} -v $(pwd):/travis ${IMAGE} tail -f /dev/null

install:
  - docker exec -t ${NAME} bash -c "${UPDATE_CMD}"
  - docker exec -t ${NAME} bash -c "${UPGRADE_CMD}"
  - docker exec -t ${NAME} bash -c "${INSTALL_CMD}"

script:
  # Check the autotools build.
  - docker exec -t ${NAME} bash -c "cd /travis;
      ./bootstrap && ./configure && make distcheck"
  # Check the cmake build.
  - docker exec -t ${NAME} bash -c "cd /travis;
      mkdir distcheck-cmake && cd distcheck-cmake &&
        tar -xvzf ../centerim5-*.tar.gz && cmake centerim5-* &&
        make && make check"
  # Build the documentation.
  - docker exec -t ${NAME} bash -c "cd /travis; make doc"
