#! /bin/sh
# script shamelessly taken from openbox

sh() {
  /bin/sh -c "set -x; $*" || exit 1
}

sh autopoint --force # for GNU gettext
sh libtoolize --copy --force --quiet
sh aclocal -I m4
sh autoheader
sh autoconf
sh automake --add-missing --copy

echo
echo You are now ready to run ./configure
echo Enjoy!
