#! /bin/sh
# script shamelessly taken from openbox

sh() {
  /bin/sh -c "set -x; $*"
}

# TODO autopoint from gettext 0.18 contains support for multiple po
# directories, split cppconsui/cim po directory when it comes out...
mkdir build
cd build
CFLAGS="-std=c99" cmake ../
cd ..

echo
echo You are now ready to run make in the build/ directory
echo For further options run ccmake ../ in build/ directory
echo enjoy!
