.TH CENTERIM5 1 "11 July 2016"

.SH NAME
centerim5 \- a text\-mode instant messaging client

.SH SYNOPSIS
\fBcenterim5\fR [\fB\-a\fR] [\fB\-b\fR \fIDIR\fR] [\fB\-o\fR]

.SH DESCRIPTION
\fBcenterim5\fR is a text\-mode IM client for Linux, *BSD, Solaris and other
Unices that uses libpurple as a communication backend.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-ascii\fR
Use ASCII characters to draw lines and boxes.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display command line usage.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show the program version info.
.TP
\fB\-b\fR \fIDIR\fR, \fB\-\-basedir\fR=\fIDIR\fR
Specify another base directory; useful for having several IM identities under
the same UNIX account.
.TP
\fB\-o\fR, \fB\-\-offline\fR
Start with all accounts set offline.

.SH BUGS
Please send bug reports to <centerim-devel@centerim.org>.

.SH "SEE ALSO"
<http://www.centerim.org/>, \fBfinch\fR(1), \fBpidgin\fR(1)
