.TH CENTERIM5 1 "22 July 2011"

.SH NAME
\fBcenterim5\fP \- a text-mode IM client for Linux, *BSD, Solaris and other
Unices that uses libpurple as a communication backend.

.SH SYNOPSIS
.B "centerim5 "
[
.B option
] ...

.SH DESCRIPTION
This manual page documents briefly the
.B centerim5
command.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-ascii\fR
use ASCII characters to draw lines and boxes
.TP
\fB\-h\fR, \fB\-\-help\fR
display command line usage
.TP
\fB\-v\fR, \fB\-\-version\fR
show the program version info
.TP
\fB\-b\fR, \fB\-\-basedir\fR <directory>
specify another base directory; useful for having several IM identities
under the same UNIX account
.TP
\fB\-o\fR, \fB\-\-offline\fR
start with all protocols set offline

.SH BUG REPORT
Report any bugs at our Bugzilla site at http://bugzilla.centerim.org/

.SH WEB
http://www.centerim.org/
